### ISSUE TITLE
Modern Browser 번역

### ISSUE THREAD

**Issue by bestalign** [item4/js-the-right-way#11]
"현대적인" 보다 "모던"이 나을거라 생각합니다. 보통 "모던 브라우저"라고 이야기들 하니까요.

94585d46c1150bddd20157f24000ef0187f1fca9
f7f10dd9e29be3f85562dc12c5a4449792dccf0c
cc4f15b6aa7c91187c15980ad367412edb57e712
e05048fccc365644f73bbeabd76b71e0c7c6efa3

**Comment by item4** [comment]
네. 제 생각에도 그런 것 같습니다. 수정해서 올리겠습니다.

**Comment by item4** [comment]
수정 완료
