### ISSUE TITLE
번역시 반말/높임말 사용

### ISSUE THREAD

**Issue by bestalign** [item4/js-the-right-way#4]
번역시 모두 높임말로 통일 했으면 합니다.
5bb1ede34d66d1b735cb9a46b7d85a8b8e910c08
bd5dd14a0c50e1f8055c3aa76406879a70547ede
ba19fdc12d673dbfb337c7e37b5e92c96c313c2e

**Comment by item4** [comment]
높임말로 통일하는 것에 찬성합니다. :+1:

**Comment by bestalign** [comment]
https://github.com/item4/js-the-right-way/issues/3 가 처리되면 issue 닫아주세요 :+1:
